server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

loadbalancer.ribbon.enabled: false

spring:
  cloud:
    gateway:
      discovery.locator: # enables the Gateway to create routes based on services registered with service discovery
        enabled: true
        lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"